#cloud-config
autoinstall:
  version: 1
  identity:
    realname: 'Enzo Kniggendorf'
    hostname: kniggendorfpc
    username: kniggendorf
    password: '$y$j9T$gA8I.KcPfc1vXSve93bLd0$DcfgaOmIn75QieWyKrcHCCXPhfQtn0Lpn5oayr0W7r5'
  locale: pt_BR.utf8
  keyboard:
    layout: br
  timezone: "America/Sao_Paulo"
  packages:
    - gimp
    - git
    - wget
    - code
    - flatpak
  runcmd:
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak install -y flathub com.brave.Browser
    - flatpak install -y flathub com.discordapp.Discord
    - flatpak install -y flathub com.spotify.Client
  codecs:
    install: true
  drivers:
    install: true
  updates: all
  shutdown:
    prompt: true
