#cloud-config
autoinstall:
  version: 1
  identity:
    realname: 'Enzo Kniggendorf'
    hostname: kniggendorfpc
    username: kniggendorf
    no-password: true 
  locale: pt_BR.utf8
  keyboard:
    layout: br
  timezone: "America/Sao_Paulo"
  packages:
    - gimp
    - git
    - wget
  snaps:
    - name: code
      channel: stable
      classic: true
    - name: brave
      channel: stable
      classic: false
    - name: discord
      channel: stable
      classic: false
  codecs:
    install: true
  drivers:
    install: true
  updates: all
  shutdown: reboot
